-- CBS Staging Schema Initialization for BNPL Platform
-- Schema: INT_STG
-- This script creates all staging tables required for the BNPL-to-CBS EOD integration.
-- Run this on the CBS staging database before deploying the BNPL platform.

CREATE SCHEMA IF NOT EXISTS INT_STG;

-- 5.2.1 STG_TXN_HEADER — Transaction Header
CREATE TABLE IF NOT EXISTS INT_STG.STG_TXN_HEADER (
    STG_HEADER_ID           BIGINT          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CORRELATION_ID          VARCHAR(64)     NOT NULL,
    BATCH_ID                VARCHAR(64)     NOT NULL,
    SOURCE_SYSTEM           VARCHAR(32)     NOT NULL DEFAULT 'BNPL_PLATFORM',
    SOURCE_REF_NO           VARCHAR(128)    NOT NULL,
    SOURCE_TIMESTAMP        TIMESTAMP(3)    NOT NULL,

    TXN_TYPE                VARCHAR(16)     NOT NULL,
    TXN_CATEGORY            VARCHAR(32)     NOT NULL,
    TXN_CODE                VARCHAR(16)     NULL,
    TXN_CURRENCY            CHAR(3)         NOT NULL DEFAULT 'LAK',
    TXN_AMOUNT              DECIMAL(19,4)   NOT NULL,
    TXN_AMOUNT_LCY          DECIMAL(19,4)   NULL,
    EXCHANGE_RATE           DECIMAL(19,8)   NULL,

    DEBIT_ACCOUNT_NO        VARCHAR(34)     NULL,
    CREDIT_ACCOUNT_NO       VARCHAR(34)     NULL,
    DEBIT_ACCOUNT_BRANCH    VARCHAR(8)      NULL,
    CREDIT_ACCOUNT_BRANCH   VARCHAR(8)      NULL,

    BNPL_TXN_CATEGORY       VARCHAR(32)     NULL,
    BNPL_MERCHANT_ID        VARCHAR(32)     NULL,
    BNPL_CONSUMER_ID        VARCHAR(32)     NULL,
    BNPL_INSTALLMENT_REF    VARCHAR(64)     NULL,
    BNPL_AUTH_ID            VARCHAR(64)     NULL,
    MDR_RATE                DECIMAL(5,4)    NULL,
    MDR_AMOUNT              DECIMAL(19,4)   NULL,
    NET_SETTLEMENT_AMOUNT   DECIMAL(19,4)   NULL,

    STG_STATUS              VARCHAR(16)     NOT NULL DEFAULT 'PENDING',
    STG_STATUS_TIMESTAMP    TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    EOD_BATCH_RUN_ID        VARCHAR(64)     NULL,
    EOD_PICKUP_TIMESTAMP    TIMESTAMP(3)    NULL,
    EOD_POSTING_TIMESTAMP   TIMESTAMP(3)    NULL,
    EOD_FAILURE_REASON      VARCHAR(512)    NULL,

    RETRY_COUNT             SMALLINT        NOT NULL DEFAULT 0,
    MAX_RETRIES             SMALLINT        NOT NULL DEFAULT 3,
    HOLD_REASON             VARCHAR(128)    NULL,

    CREATED_BY              VARCHAR(32)     NOT NULL DEFAULT 'BNPL_INTEGRATION',
    CREATED_TIMESTAMP       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY             VARCHAR(32)     NULL,
    MODIFIED_TIMESTAMP      TIMESTAMP(3)    NULL,

    CONSTRAINT uq_correlation UNIQUE (CORRELATION_ID),
    CONSTRAINT chk_status CHECK (STG_STATUS IN ('PENDING','PICKED','POSTED','FAILED','REVERTED','HELD')),
    CONSTRAINT chk_amount_positive CHECK (TXN_AMOUNT >= 0),
    CONSTRAINT chk_debit_or_credit CHECK (
        (TXN_TYPE = 'DEBIT' AND DEBIT_ACCOUNT_NO IS NOT NULL) OR
        (TXN_TYPE = 'CREDIT' AND CREDIT_ACCOUNT_NO IS NOT NULL) OR
        (TXN_TYPE = 'TRANSFER' AND DEBIT_ACCOUNT_NO IS NOT NULL AND CREDIT_ACCOUNT_NO IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_stg_header_status ON INT_STG.STG_TXN_HEADER(STG_STATUS) WHERE STG_STATUS = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_stg_header_batch ON INT_STG.STG_TXN_HEADER(BATCH_ID, STG_STATUS);
CREATE INDEX IF NOT EXISTS idx_stg_header_source ON INT_STG.STG_TXN_HEADER(SOURCE_SYSTEM, SOURCE_REF_NO);
CREATE INDEX IF NOT EXISTS idx_stg_header_eod_run ON INT_STG.STG_TXN_HEADER(EOD_BATCH_RUN_ID);
CREATE INDEX IF NOT EXISTS idx_stg_header_created ON INT_STG.STG_TXN_HEADER(CREATED_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_stg_header_bnpl ON INT_STG.STG_TXN_HEADER(BNPL_CONSUMER_ID, BNPL_MERCHANT_ID);

-- 5.2.2 STG_TXN_DETAIL — Transaction Line Items (1:N)
CREATE TABLE IF NOT EXISTS INT_STG.STG_TXN_DETAIL (
    STG_DETAIL_ID           BIGINT          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STG_HEADER_ID           BIGINT          NOT NULL REFERENCES INT_STG.STG_TXN_HEADER(STG_HEADER_ID),
    LINE_NO                 SMALLINT        NOT NULL,

    DETAIL_TYPE             VARCHAR(16)     NOT NULL,
    DETAIL_AMOUNT           DECIMAL(19,4)   NOT NULL,
    DETAIL_CURRENCY         CHAR(3)         NOT NULL DEFAULT 'LAK',
    GL_ACCOUNT_CODE         VARCHAR(16)     NULL,
    COST_CENTER             VARCHAR(16)     NULL,
    PROFIT_CENTER           VARCHAR(16)     NULL,

    NARRATIVE_LINE1         VARCHAR(140)    NULL,
    NARRATIVE_LINE2         VARCHAR(140)    NULL,
    NARRATIVE_LINE3         VARCHAR(140)    NULL,
    NARRATIVE_LINE4         VARCHAR(140)    NULL,

    FLEX_FIELD_1            VARCHAR(128)    NULL,
    FLEX_FIELD_2            VARCHAR(128)    NULL,
    FLEX_FIELD_3            VARCHAR(128)    NULL,
    FLEX_FIELD_4            VARCHAR(128)    NULL,
    FLEX_FIELD_5            VARCHAR(128)    NULL,

    CREATED_TIMESTAMP       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_header_line UNIQUE (STG_HEADER_ID, LINE_NO)
);

-- 5.2.3 STG_TXN_CONTROL — Batch Control & Handshake
CREATE TABLE IF NOT EXISTS INT_STG.STG_TXN_CONTROL (
    BATCH_ID                VARCHAR(64)     PRIMARY KEY,
    SOURCE_SYSTEM           VARCHAR(32)     NOT NULL DEFAULT 'BNPL_PLATFORM',

    EXPECTED_RECORD_COUNT   INTEGER         NOT NULL,
    EXPECTED_TOTAL_AMOUNT   DECIMAL(19,4)   NOT NULL,
    EXPECTED_TOTAL_AMOUNT_LCY DECIMAL(19,4) NULL,
    EXPECTED_CURRENCY       CHAR(3)         NOT NULL DEFAULT 'LAK',

    ACTUAL_RECORD_COUNT     INTEGER         NULL,
    ACTUAL_TOTAL_AMOUNT     DECIMAL(19,4)   NULL,
    ACTUAL_TOTAL_AMOUNT_LCY DECIMAL(19,4)   NULL,

    CONTROL_STATUS          VARCHAR(16)     NOT NULL DEFAULT 'OPEN',
    CONTROL_STATUS_TIMESTAMP TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    EOD_BATCH_RUN_ID        VARCHAR(64)     NULL,
    EOD_START_TIMESTAMP     TIMESTAMP(3)    NULL,
    EOD_END_TIMESTAMP       TIMESTAMP(3)    NULL,

    RECONCILE_STATUS        VARCHAR(16)     NULL,
    RECONCILE_DIFFERENCE    DECIMAL(19,4)   NULL,
    RECONCILE_TIMESTAMP     TIMESTAMP(3)    NULL,

    CREATED_TIMESTAMP       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_TIMESTAMP      TIMESTAMP(3)    NULL,

    CONSTRAINT chk_control_status CHECK (CONTROL_STATUS IN ('OPEN','READY_FOR_PICKUP','IN_PROGRESS','COMPLETED','PARTIAL','FAILED'))
);

-- 5.2.4 Supporting Tables
CREATE TABLE IF NOT EXISTS INT_STG.STG_ERROR_LOG (
    ERROR_ID                BIGINT          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STG_HEADER_ID           BIGINT          NULL REFERENCES INT_STG.STG_TXN_HEADER(STG_HEADER_ID),
    BATCH_ID                VARCHAR(64)     NOT NULL,
    ERROR_PHASE             VARCHAR(32)     NOT NULL,
    ERROR_CODE              VARCHAR(16)     NOT NULL,
    ERROR_SEVERITY          VARCHAR(8)      NOT NULL,
    ERROR_MESSAGE           VARCHAR(2000)   NOT NULL,
    ERROR_STACK             TEXT            NULL,
    ERROR_TIMESTAMP         TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RESOLVED_FLAG           CHAR(1)         NOT NULL DEFAULT 'N',
    RESOLVED_TIMESTAMP      TIMESTAMP(3)    NULL,
    RESOLVED_BY             VARCHAR(32)     NULL
);

CREATE TABLE IF NOT EXISTS INT_STG.STG_RECONCILE (
    RECONCILE_DATE          DATE            NOT NULL,
    SOURCE_SYSTEM           VARCHAR(32)     NOT NULL,
    BATCH_ID                VARCHAR(64)     NOT NULL,

    STAGED_COUNT            INTEGER         NOT NULL,
    STAGED_AMOUNT           DECIMAL(19,4)   NOT NULL,
    POSTED_COUNT            INTEGER         NOT NULL,
    POSTED_AMOUNT           DECIMAL(19,4)   NOT NULL,
    FAILED_COUNT            INTEGER         NOT NULL,
    FAILED_AMOUNT           DECIMAL(19,4)   NOT NULL,
    HELD_COUNT              INTEGER         NOT NULL,
    HELD_AMOUNT             DECIMAL(19,4)   NOT NULL,

    DIFFERENCE_COUNT        INTEGER         NOT NULL,
    DIFFERENCE_AMOUNT       DECIMAL(19,4)   NOT NULL,

    STATUS                  VARCHAR(16)     NOT NULL,
    RECONCILE_TIMESTAMP     TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (RECONCILE_DATE, BATCH_ID)
);

CREATE TABLE IF NOT EXISTS INT_STG.STG_AUDIT_TRAIL (
    AUDIT_ID                BIGINT          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPERATION               VARCHAR(16)     NOT NULL,
    TABLE_NAME              VARCHAR(32)     NOT NULL,
    RECORD_ID               BIGINT          NOT NULL,
    USER_ID                 VARCHAR(32)     NOT NULL,
    TIMESTAMP               TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CLIENT_IP               VARCHAR(45)     NULL,
    SESSION_ID              VARCHAR(128)    NULL,
    OLD_VALUES              JSONB           NULL,
    NEW_VALUES              JSONB           NULL
);

-- Database Roles (run separately by CBS DBA)
-- CREATE ROLE BNPL_STG_WRITER;
-- GRANT INSERT ON INT_STG.STG_TXN_HEADER, INT_STG.STG_TXN_DETAIL TO BNPL_STG_WRITER;
-- GRANT SELECT ON INT_STG.STG_TXN_CONTROL TO BNPL_STG_WRITER;
--
-- CREATE ROLE BNPL_STG_READER;
-- GRANT SELECT ON ALL TABLES IN SCHEMA INT_STG TO BNPL_STG_READER;
--
-- CREATE ROLE CBS_EOD_USER;
-- GRANT SELECT, UPDATE ON ALL TABLES IN SCHEMA INT_STG TO CBS_EOD_USER;
-- GRANT INSERT ON INT_STG.STG_ERROR_LOG, INT_STG.STG_RECONCILE TO CBS_EOD_USER;
